version: '3'

services:
  db:
    image: 'postgres:13.6-alpine'
    ports:
      - '5432:5432'
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: r02_db
      POSTGRES_USER: r02_db_user
      POSTGRES_PASSWORD: password
