version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    command: bundle exec rails server -b 0.0.0.0
    environment:
      TZ: Asia/Tokyo
      LANG: C.UTF-8
      RAILS_ENV: development
    volumes:
      - ./backend:/backend
