version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    command: bundle exec rails server -b 0.0.0.0
    environment:
      TZ: Asia/Tokyo
      LANG: C.UTF-8
      RAILS_ENV: development
    volumes:
      - .:/backend
  db:
    image: 'postgres:13.6-alpine'
    ports:
      - '5432:5432'
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: r02_db
      POSTGRES_USER: r02_db_user
      POSTGRES_PASSWORD: password
