default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("RAILS_DATABASE_HOST") { '0.0.0.0' } %>
  port: <%= ENV.fetch("RAILS_DATABASE_PORT") { '5432' } %>
  database: r02_db
  username: r02_db_user
  password: <%= ENV.fetch("RAILS_DATABASE_PASSWORD") { 'password' } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
