name: lint

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
      - run: |
          gem install bundler:2.3.6
          bundle install --jobs 4 --retry 3
      - run: bash .github/scripts/run_rubocop.sh
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
