name: test

on:
  push:

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      db:
        image: 'postgres:13.6-alpine'
        ports:
          - '5432:5432'
        env:
          TZ: Asia/Tokyo
          POSTGRES_DB: r02_db
          POSTGRES_USER: r02_db_user
          POSTGRES_PASSWORD: password
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - run: |
          gem install bundler:2.0.1
          bundle install --jobs 4 --retry 3
      - run: RAILS_ENV=test bundle exec rake db:migrate
      - run: bundle exec rspec
